config/routes.rb
Rails.application.routes.draw do
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'
  get '/406', to: 'errors#unacceptable'

  Book.all.each do |book|
    get "/#{book.slug}", to: 'books#show'
    get "/#{book.slug}/:chapter_slug", to: 'chapters#show'
  end

  # get '/:book_slug', to: 'books#show', as: :book
  # get '/:book_slug/:chapter_slug', to: 'chapters#show', as: :chapter

  root "pages#home"
end

app/models/book.rb
class Book
  include ActiveModel::Model

  attr_accessor :title, :description, :keywords, :pitch, :author, :author_url, :credits, :chapters, :published_at, :updated_at


  def slug
    title.parameterize
  end


  def first_chapter
    chapter = chapters.first
    raise ActionController::RoutingError, "Not Found" unless chapter
    chapter
  end


  def next_chapter current_chapter
    chapters[chapters.index(current_chapter) + 1]
  end


  def find_chapter slug
    chapters.find { |chapter| chapter.slug == slug }
  end


  def author
    @author ||= "Perky Crow"
  end


  def updated_at
    @updated_at ||= published_at
  end


  def cover_path
    "books/#{slug.underscore}/cover.png"
  end



  def self.all
    [book1]
  end


  def self.find slug
    book = all.find { |book| book.slug == slug }
    raise ActionController::RoutingError, "Not Found" unless book
    book
  end


  def self.book1
    new(
      title:        "A JavaScript Odyssey",
      description:  "Embark on a personal journey of game development with A JavaScript Odyssey",
      published_at: "February 2023",
      keywords:     "HTML5, CSS3, Canvas, requestAnimationFrame, no lib, no framework, book",
      pitch:        %{
        Discover our approach to building games from scratch.

        Explore the world of pure **JavaScript game development** as you follow along with the creation of a mini-game.

        Whether you're a **curious** non-developer, an advanced **developer** seeking inspiration, or a **beginner** looking to build your own tools, this book has something for you.

        With practical insights, this book will show you how to create games without relying on frameworks or libraries.
      },
      author:       "Perky Crow",
      author_url:   "https://www.perkycrow.com",
      credits:      %{
        Game Art & Illustrations by [**Ash**](https://www.instagram.com/ashmosnier/) |
        Written by [**Hugeen**](https://hugeen.com/)
      },
      chapters: [
        Chapter.new(
          name:        "Prologue",
          title:       "A fallen Hero",
          description: "Explore the rise of HTML5 and the fall of Flash in the world of game development with the prologue of A JavaScript Odyssey",
          keywords:    "HTML5, Flash, Adobe, game development, history"
        ),
        Chapter.new(
          name:        "Chapter 1",
          title:       "Fresh start",
          description: "Learn how to create JavaScript games without extra libraries or tools",
          keywords:    "Pure JavaScript, VSCode, chrome, http, server, coding, basics, game development"
        ),
        Chapter.new(
          name:        "Chapter 2",
          title:       "The Canvas",
          description: "Discover the benefits of using the Canvas API for creating mini-games",
          keywords:    "Canvas, fillRect, fillColor, drawImage, Promise, loadImage, MDN, Canvas API"
        ),
        Chapter.new(
          name:        "Chapter 3",
          title:       "Painting a scene",
          description: "Composing a game scene using only JavaScript and the Canvas API",
          keywords:    "Canvas, fillRect, fillColor, drawImage, Promise, loadImage, MDN, Canvas API"
        ),
        Chapter.new(
          name:        "Chapter 4",
          title:       "Movement",
          description: "Animating a side scroller game using a camera",
          keywords:    "Canvas, Camera, requestAnimationFrame, game loop, game development"
        ),
        Chapter.new(
          name:        "Chapter 5",
          title:       "Infinite world",
          description: "Generating a world with a procedural algorithm",
          keywords:    "procedural generation, random, world generation, game development",
        ),
        Chapter.new(
          name:        "Chapter 6",
          title:       "Hero",
          description: "Animating a hero with a sprite sheet and making it jump",
          keywords:    "Sprite sheet, animation, jump, game development"
        ),
        Chapter.new(
          name:        "Chapter 7",
          title:       "Obstacles",
          description: "Generating obstacles and making the hero collide with them",
          keywords:    "Collision, game development, obstacles, canvas, JavaScript"
        ),
        Chapter.new(
          name:        "Chapter 8",
          title:       "From toy to game",
          description: "Learn how to turn your toy into a game",
          keywords:    "game development, game design, game loop, game engine, game architecture"
        ),
        Chapter.new(
          name:        "Chapter 9",
          title:       "End",
          description: "Learn about game development approaches and get insights on how to develop games using pure JavaScript",
          keywords:    "PIXI.js, Discord, Twitter, insights"
        )
      ]
    )
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  layout "book"

  def show
    slug = request.path.split("/")[1]
    @book = Book.find(slug)
  end

end

app/helpers/books_helper.rb
module BooksHelper

  def book_link_class book
    request.path == book_path(book) ? 'active' : nil
  end

  def book_illustration book, src, alt = nil, title = nil
    illustration("books/#{book.slug.underscore}/#{src}", alt, title)
  end

  def book_path book
    "/#{book.slug}"
  end

end

app/views/books/_menu.html.erb
<div class="menu">
  <nav>
    <ul>
      <li class="<%= book_link_class(book) %>">
        <%= link_to book_path(book) do %>
          <span class="category">Introduction</span>
          <span class="title"><%= book.title %></span>
        <% end %>
      </li>
      <% book.chapters.each do |chapter| %>
        <li class="<%= chapter_link_class(book, chapter) %>">
          <%= link_to chapter_path(book, chapter) do %>
            <span class="category"><%= numeral_to_roman(chapter.name) %></span>
            <span class="title"><%= chapter.title %></span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </nav>
</div>

app/views/books/show.html.erb
<%= content_for :title, @book.title %>
<%= content_for :image_url, @book.cover_path %>
<%= content_for :description, @book.description %>
<%= content_for :keywords, @book.keywords %>


<div class="book">
  <h1 class="title"><%= @book.title %></h1>
  <div class="info">Published in <%= @book.published_at %> by <%= link_to @book.author, @book.author_url, target: "_blank" %></div>
  <div class="cover"><%= image_tag @book.cover_path, alt: "Book cover for #{@book.title}" %></div>
  <div class="pitch"><%= simple_markdown @book.pitch %></div>

  <% if @book.credits %>
    <div class="credits"><%= simple_markdown @book.credits %></div>
  <% end %>
</div>

<div class="separator"><%= image_tag "separator.png" %></div>

<div class="read_next">
  <span class="category">Next: <%= @book.first_chapter.name %></span><br>
  <%= link_to @book.first_chapter.title, chapter_path(@book, @book.first_chapter) %>
</div>